#!/bin/sh
set -e
# first arg is `-f` or `--some-option`
if [ "bash" = "$1" ] || [ "/bin/bash" = "$1" ]; then
  exec "$@"
else
  if [ "${1#-}" != "$1" ]; then
    set -- apache2-foreground "$@"
  fi
  /usr/local/bin/boot-container.sh
  exec "$@"
fi
