
name: Release
on: 
  workflow_call:
    inputs:
      SW_VERSION:
        type: string
        required: true
        description: Shopware Version
      PHP_VERSION:
        type: string
        required: true
        description: Shopware Version
  release:
    types: ["published"]

jobs:
  release:
    needs:
     - build
     - detect_version
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Set outputs
        shell: bash
        id: vars
        run: |
          SW_VERSION="${{inputs.SW_VERSION}}"
          echo "::set-output name=DOCKER_TAG::${{inputs.SW_VERSION}}-${{inputs.PHP_VERSION}}-$(git rev-parse --short HEAD)"
          echo "::set-output name=DOCKER_MAIN_TAG::${{inputs.SW_VERSION}}"
          echo "::set-output name=DOCKER_IMAGE::forestsoft/shopware"
          echo "::set-output name=SW_MAJOR::${SW_VERSION:0:1}"
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Image
        run: |
          MINOR_RELEASE=$(echo "${{inputs.SW_VERSION}}" | grep -Po '^(\d\.\d+)'")
          docker pull ${{ steps.vars.outputs.DOCKER_IMAGE }}:${{ steps.vars.outputs.DOCKER_TAG }}
          docker tag ${{ steps.vars.outputs.DOCKER_IMAGE }}:${{ steps.vars.outputs.DOCKER_TAG }} ${{ steps.vars.outputs.DOCKER_IMAGE }}:$MINOR_RELEASE
          docker push ${{ needs.build.outputs.DOCKER_IMAGE }}:$MINOR_RELEASE